name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:sql/images.db
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          cargo install sqlx-cli
          sh ./sql/create-db.sh
          cargo sqlx prepare --database-url $DATABASE_URL
      - name: Run Clippy
        run: |
          cargo clippy --all-targets --all-features
  
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:sql/images.db
      INI_CONFIGURATION: configuration.ini
    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        cargo install sqlx-cli
        sh ./sql/create-db.sh
        cargo sqlx prepare --database-url $DATABASE_URL
    - uses: docker://lpenz/ghaction-rust-coverage:0.12.0
    - uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
        path-to-lcov: ./lcov.info
